apiVersion: integration.ibm.com/v1beta1
kind: PlatformNavigator
metadata:
    name: integration-navigator
    namespace: cp4i
spec:
    license:
        accept: true
        license: L-RJON-BZFQU2
    mqDashboard: true
    replicas: 1
    storage:
        class: "storage_class"
    version: 2021.2.1
    requestIbmServices:
        licensing: true
        monitoring: true 
