apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
 name: common-services-es
 namespace: openshift-cluster-node-tuning-operator
spec:
 profile:
 - data: |
     [sysctl]
     vm.max_map_count=262144
   name: common-services-es
 recommend:
 - priority: 10
   profile: common-services-es