apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-cp-integration.openshift-operators: ""
  name: ibm-cp-integration
  namespace: openshift-operators
spec:
  channel: v1.2
  installPlanApproval: Automatic
  name: ibm-cp-integration
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-cp-integration.v1.2.0