apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
spec:
  resources:
    mds:
      limits:
        cpu: "3"
        memory: "8Gi"
      requests:
        cpu: "3"
        memory: "8Gi"
  managedResources:
    cephBlockPools: 
      reconcileStrategy: manage
    cephFilesystems: 
      reconcileStrategy: manage
    cephObjectStoreUsers: 
      reconcileStrategy: manage
    cephObjectStores: 
      reconcileStrategy: manage
    snapshotClasses:
      reconcileStrategy: manage
    storageClasses:
      reconcileStrategy: manage
  monDataDirHostPath: /var/lib/rook
  storageDeviceSets:
    - config: {}
      count: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: '1'
          storageClassName: localblock
          volumeMode: Block
      name: ocs-deviceset-localblock
      placement: {}
      replica: 3
      resources: 
        limits:
          cpu: "2"
          memory: "5Gi"
        requests:
          cpu: "2"
          memory: "5Gi"

